
from fastapi import APIRouter
from fastapi.responses import HTMLResponse
from backend.caching.loader import loader
import pandas as pd
from datetime import datetime

router = APIRouter()

@router.get("/pdf", response_class=HTMLResponse)
def get_pdf_report():
    df = loader.get_customer_snapshot()
    
    # KPIs
    total_customers = len(df)
    avg_clv = df["clv_12m"].mean() if not df.empty else 0
    churn_rate = (df["churn_probability"].mean() * 100) if not df.empty else 0
    
    # Segments
    segments_html = ""
    if "segment_name" in df:
        seg_counts = df["segment_name"].value_counts().reset_index()
        seg_counts.columns = ["Segment", "Count"]
        segments_html = seg_counts.to_html(classes="table", index=False)
        
    # High Risk
    high_risk = df[df["churn_probability"] > 0.8].head(10)[["customer_id", "clv_12m", "churn_probability"]]
    risk_html = high_risk.to_html(classes="table", index=False)

    html_content = f"""
    <html>
    <head>
        <title>Customer Intelligence Report</title>
        <style>
            body {{ font-family: sans-serif; padding: 40px; color: #333; }}
            h1 {{ color: #000; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            h2 {{ color: #444; margin-top: 30px; }}
            .kpi-container {{ display: flex; gap: 20px; margin-bottom: 40px; }}
            .kpi-card {{ border: 1px solid #ddd; padding: 20px; border-radius: 8px; flex: 1; text-align: center; }}
            .kpi-value {{ font-size: 24px; font-weight: bold; color: #007bff; }}
            .kpi-label {{ font-size: 14px; color: #666; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f8f9fa; }}
            @media print {{
                .no-print {{ display: none; }}
            }}
        </style>
    </head>
    <body onload="window.print()">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <h1>Customer Intelligence Report</h1>
            <p>{datetime.now().strftime("%Y-%m-%d")}</p>
        </div>

        <div class="kpi-container">
            <div class="kpi-card">
                <div class="kpi-value">{total_customers:,}</div>
                <div class="kpi-label">Total Customers</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">${avg_clv:,.2f}</div>
                <div class="kpi-label">Average CLV</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-value">{churn_rate:.1f}%</div>
                <div class="kpi-label">Avg Churn Risk</div>
            </div>
        </div>

        <h2>Segment Distribution</h2>
        {segments_html}

        <h2>Top Critical Risk Customers</h2>
        {risk_html}
        
        <div style="margin-top: 50px; text-align: center; color: #888; font-size: 12px;">
            Generated by Gravity AI
        </div>
    </body>
    </html>
    """
    return html_content
